### ISSUE TITLE
pip3 install fails due to glmnet_py git version vs pip version

### ISSUE THREAD

**Issue by tseemann** [mgalardini/pyseer#101]
It seems you want a git version of `glmnet_py` that isn't in pip?
```
% python3 -m pip install pyseer

Collecting glmnet_py
  Downloading https://files.pythonhosted.org/packages/f5/1a/55b708789a66f2405783bce0f53e02b86128ea3f21d329c87dc6dbef8e51/glmnet_py-0.1.0b2.tar.gz (1.2MB)
     |████████████████████████████████| 1.2MB 24.3MB/s
    ERROR: Command errored out with exit status 1:
     command: /home/linuxbrew/.linuxbrew/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y3jr_1iw/glmnet-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y3jr_1iw/glmnet-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-y3jr_1iw/glmnet-py/pip-egg-info
         cwd: /tmp/pip-install-y3jr_1iw/glmnet-py/
    Complete output (6 lines):
    sh: gfortran: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y3jr_1iw/glmnet-py/setup.py", line 11, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mgalardini** [comment]
Hi Torsten,

the best way to get around this is to use conda, as `glmnet_py` requires some compilation; I will look into this, but maybe you can try install `gfortran` first?

M

**Comment by tseemann** [comment]
@mgalardini i just realised that was the real error - missing `gfortran` - trying to fix now. !

**Comment by tseemann** [comment]
It has gotten further - but i think i'll need to install the git version?
```
    Complete output (6 lines):
    gfortran: error: ./glmnet_py/GLMnet.f: No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dvf_22x5/glmnet-py/setup.py", line 11, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by tseemann** [comment]
This works:
```
pip3 install git+https://github.com/hanfang/glmnet_py.git

    Running setup.py install for glmnet-py ... done
Successfully installed glmnet-py-0.1.0b1
```
Do i need the exact commit you specify?

**Comment by mgalardini** [comment]
Thanks for inspecting this; yeah, I think we need to change the `setup.py` entry, as indicated [here](https://stackoverflow.com/a/32689886/1237531)

**Comment by mgalardini** [comment]
And no, I don't believe we require an exact commit
