### ISSUE TITLE
Pyseer unable to parallelize job larger than 2GB

### ISSUE THREAD

**Issue by mgro** [mgalardini/pyseer#104]
Hi,

I'm trying to run the elastic net model implemented in pyseer on a large input file of unitigs (23.84GB), provoking the error message below. I run pyseer 1.3.3. through conda (64 bit python 3.7.3). Has anyone encountered this yet and found a work around? 

```[status]	Parallel glmnet cv with 8 cores
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 344, in _sendback_result
    exception=exception))
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/site-packages/joblib/externals/loky/backend/queues.py", line 240, in put
    self._writer.send_bytes(obj)
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mg451/software/miniconda3/envs/pyseer/bin/pyseer", line 10, in <module>
    sys.exit(main())
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/site-packages/pyseer/__main__.py", line 631, in main
    lineage_dict, fold_ids, options.n_folds, options.cpu)
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/site-packages/pyseer/enet.py", line 174, in fit_enet
    foldid = fold_ids, alpha = alpha, parallel = n_cpus, weights = weights)
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/site-packages/glmnet_python/cvglmnet.py", line 283, in cvglmnet
    cpredmat = joblib.Parallel(n_jobs=num_cores)(joblib.delayed(doCV)(i, x, y, family, foldid, nfolds, is_offset, **options) for i in range(nfolds))
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/site-packages/joblib/parallel.py", line 1016, in __call__
    self.retrieve()
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/site-packages/joblib/parallel.py", line 908, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 554, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/mg451/software/miniconda3/envs/pyseer/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

**Comment by mgalardini** [comment]
Hi,

those seem like a lot of unitigs! How many samples do you have, and do they belong to the same species? One thing that comes to mind is that if a few samples are very different or of low quality they could lead to a sharp increase in the number of unitigs/kmers.

Hope this helps,
Marco

**Comment by mgro** [comment]
Hi Marco,
indeed, it's a large collection of ~1400 diverse isolates belonging to one species however at ANI's between 90 and 100, so this is certainly the reason for having so many unitigs.

I solved this issue by just running the analysis on one thread to circumvent the multithreading. 

Thanks Marco,

Matthias
