### ISSUE TITLE
Problem with k-mer association

### ISSUE THREAD

**Issue by mi3112** [mgalardini/pyseer#132]
I´m trying to do the same as the GWAS tutorial, but with unitigs obtain with unitig-counter. I´m using this code:

pyseer --lmm --phenotypes resistance_phenotype_imp.pheno --kmers unitigs.txt.gz --similarity phylogeny_K.tsv --output-patterns kmer_patterns_imp.txt --cpu 8 > imipenem_kmers.txt

But I don´t having any result, only this  warning

Read 416 phenotypes
Detected binary phenotype
Setting up LMM
Similarity matrix has dimension (416, 416)
Analysing 415 samples found in both phenotype and similarity matrix
h^2 = 0.83
Traceback (most recent call last):
  File "/home/michelle/anaconda3/bin/pyseer", line 10, in <module>
    sys.exit(main())
  File "/home/michelle/anaconda3/lib/python3.7/site-packages/pyseer/_main_.py", line 505, in main
    options.cpu))
  File "/home/michelle/anaconda3/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/michelle/anaconda3/lib/python3.7/multiprocessing/pool.py", line 383, in _map_async
    iterable = list(iterable)
  File "/home/michelle/anaconda3/lib/python3.7/site-packages/pyseer/input.py", line 500, in iter_variants_lmm
    for variants, variant_mat, eof in variant_iter:
  File "/home/michelle/anaconda3/lib/python3.7/site-packages/pyseer/input.py", line 558, in load_var_block
    sample_order)
  File "/home/michelle/anaconda3/lib/python3.7/site-packages/pyseer/input.py", line 281, in read_variant
    line_in = infile.readline()
  File "/home/michelle/anaconda3/lib/python3.7/gzip.py", line 385, in readline
    return self._buffer.readline(size)
  File "/home/michelle/anaconda3/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/michelle/anaconda3/lib/python3.7/gzip.py", line 474, in read
    if not self._read_gzip_header():
  File "/home/michelle/anaconda3/lib/python3.7/gzip.py", line 422, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'AA')

I installed pyseer using this code:
conda install -c bioconda pyseer

And ran the test with:
pytest -v tests

The message was:
44 passed, 314 warnings

How can I solve those problems?

**Comment by johnlees** [comment]
Is your unitigs input file `unitigs.txt.gz` definitely gzipped? If not, please first run:
```
gzip -c unitigs.txt.gz > tmp.gz
mv tmp.gz unitigs.txt.gz
```

**Comment by mi3112** [comment]
Thanks, I used `uncompressed` and it worked well.

Sorry for the next question, I´m new in this. In the tutorial, how do you know, after filter `penicillin_kmers.txt` with `awk`, you obtein 5327 significant k-mers?

**Comment by mgalardini** [comment]
Hi,

that should be the length of the `significant_kmers.txt` file that resulted from using awk to filter the kmers. You can run `wc -l signficicant_kmers.txt` to obtain the same number.
