### ISSUE TITLE
Prediction Tutorial Error

### ISSUE THREAD

**Issue by chaseschwarz** [mgalardini/pyseer#267]
Hi, I am attempting the prediction tutorial but am running into an issue after the first line. I believe I setup everything as indicated by installing pyseer through conda and then using un-taring the folder to have all necessary files. But I am getting this error: " FileNotFoundError: [Errno 2] No such file or directory: 'output/ma_snps.npz'". Here is the full traceback if helpful: " Traceback (most recent call last):
  File "/home/chaseps2/miniconda3/envs/pyseer/bin/pyseer", line 10, in <module>
    sys.exit(main())
  File "/home/chaseps2/miniconda3/envs/pyseer/lib/python3.10/site-packages/pyseer/__main__.py", line 623, in main
    scipy.sparse.save_npz(options.save_vars + ".npz", all_vars)
  File "/home/chaseps2/miniconda3/envs/pyseer/lib/python3.10/site-packages/scipy/sparse/_matrix_io.py", line 75, in save_npz
    np.savez_compressed(file, **arrays_dict)
  File "/home/chaseps2/miniconda3/envs/pyseer/lib/python3.10/site-packages/numpy/lib/npyio.py", line 710, in savez_compressed
    _savez(file, args, kwds, True)
  File "/home/chaseps2/miniconda3/envs/pyseer/lib/python3.10/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/chaseps2/miniconda3/envs/pyseer/lib/python3.10/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/home/chaseps2/miniconda3/envs/pyseer/lib/python3.10/zipfile.py", line 1253, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'output/ma_snps.npz'"

Thank you!

**Comment by mgalardini** [comment]
Hi, can you share the command you are using and the output of `ls output`?

**Comment by mgalardini** [comment]
Closed due to inactivity
