### ISSUE TITLE
Statsmodels > 0.9 leads to crashes

### ISSUE THREAD

**Issue by mgalardini** [mgalardini/pyseer#83]
Made a fresh mamba install of pyseer today and got this error when running `pyseer --phenotypes resistances.pheno --pres gene_presence_absence.Rtab --no-distances`

```
Read 603 phenotypes
Detected binary phenotype
Traceback (most recent call last):
  File "/home/mgala/minimamba/envs/pyseer/bin/pyseer", line 10, in <module>
    sys.exit(main())
  File "/home/mgala/minimamba/envs/pyseer/lib/python3.6/site-packages/pyseer/__main__.py", line 350, in main
    null_fit = fit_null(p.values, m, cov, options.continuous)
  File "/home/mgala/minimamba/envs/pyseer/lib/python3.6/site-packages/pyseer/model.py", line 99, in fit_null
    null_mod = smf.Logit(p, v)
AttributeError: module 'statsmodels.formula.api' has no attribute 'Logit'
```

Statsmodels is at version `0.10.0` now. I believe we either have to change the conda recipe to stay at lower versions, or add some work-arounds to handle both statsmodels flavors. I will look into it today if I can.

**Comment by mgalardini** [comment]
In case it's useful to anyone with the same issue, this hotfix would work when using conda/mamba:

```
conda remove statsmodels
conda install statsmodels=0.8.0 pyseer
```
